### ISSUE TITLE
Error when running example's classification.py

### ISSUE THREAD

**Issue by nnn112358** [AXERA-TECH/pyaxengine#16]
## Problem Description

The lastest whl  release package ([PyAXEngine 0.0.1 RC3](https://github.com/AXERA-TECH/pyaxengine/releases/tag/0.0.1rc3)) is old and an error occurs when I run examples.
The cause is Commit 9371cff.　The implementation of def load_model() has changed.
Please update the release whl package.

## Environment

```
- MCU or Board name: 
   M5Stack Module-LLM(ax630c)
- Operating System:
   Linux m5stack-LLM 4.19.125 #1 SMP PREEMPT Thu Nov 14 17:40:17 CST 2024 aarch64 aarch64 aarch64 GNU/Linux
- PyAXEngine version  
   PyAXEngine 0.0.1 RC3
```

### Actual Behavior
```
root@m5stack-LLM:# wget https://github.com/AXERA-TECH/pyaxengine/releases/download/0.0.1rc3/axengine-0.0.1-py3-none-any.whl
root@m5stack-LLM:# pip install axengine-0.0.1-py3-none-any.whl

root@m5stack-LLM:# python3 classification.py
Exception ignored in: <function InferenceSession.__del__ at 0xffffa16a5120>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/axengine/session.py", line 158, in __del__
    self._final()
  File "/usr/local/lib/python3.10/dist-packages/axengine/session.py", line 175, in _final
    if self._handle[0] is not None:
AttributeError: 'InferenceSession' object has no attribute '_handle'
Traceback (most recent call last):
  File "/opt/usr/241218_Vit/classification.py", line 99, in <module>
    main(MODEL_PATH, IMAGE_PATH, TARGET_SIZE, CROP_SIZE, K, args.backend, args.device_no)
  File "/opt/usr/241218_Vit/classification.py", line 67, in main
    session = load_model(model_path, backend, device_no)
  File "/opt/usr/241218_Vit/classification.py", line 15, in load_model
    session = axe.InferenceSession(model_path, device_no)
TypeError: InferenceSession.__init__() takes 2 positional arguments but 3 were given
```

**Comment by kalcohol** [comment]
sorry for so late，could u check this release(including example)：
https://github.com/AXERA-TECH/pyaxengine/releases/tag/0.1.0rc1

**Comment by nnn112358** [comment]
Thanks. Confirmed that the issue has been resolved with the release of PyAXEngine 0.1.0 RC1. 
I close.
